# -------------------------
# Data paths
# -------------------------
data:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  image_size: [224, 224]
  num_classes: 400

# Example ^^^^^